version: "3.4"
services:
  proxy:
    image: jjhickman/iot-home:security-cam
    container_name: security-cam
    restart: unless-stopped
    devices:
      - /dev/video0
      - /dev/vchiq
    volumes:
      - /opt/vc:/opt/vc
    network_mode: host
    environment:
      - IR_GPIO_PIN=3
      - STREAM_PORT=3333
      - STREAM_FPS=30
      - HUB_REST_ENDPOINT=http://192.168.50.166:8080
      - COOLDOWN_SECONDS=30