version: "3.4"
services:
  security-cam:
    build: .
    container_name: security-cam
    restart: unless-stopped
    devices:
      - /dev/video0
      - /dev/vchiq
#    volumes:
#      - /opt/vc:/opt/vc
    network_mode: host
    environment:
      - STREAM_PORT=3333
      - STREAM_FPS=30
      - HUB_REST_ENDPOINT=http://192.168.50.166:8080
      - THRESHOLD=30